<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

**Ways to Store and Manipulate Data:** <br>
1. Lists 
2. Numpy Arrays 
3. Dictionaries 
4. Tuples
5. Dataframes (Data Processing Basket --> Applications)
6. Classes (See: Storing Data (Nice))

## 1.1 Let’s compare

In [ ]:
import numpy as np

# Python Lists
py_super_names = ["Black Window", "Iron Man", "Doctor Strange"]
py_real names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

# Numpy Arrays
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

# Dictionary
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

- Dictionaries use a **key-value** structure separated by a `:`.
- Dictionary holds the real and super names in one structure while two lists are needed for the same data.
- For lists and arrays, **order matters**.

## 1.2 Accessing data from a list (or array)

In [1]:
# To access data from lists and arrays, call the index corresponding to the data's
# position. Note that Python starts counting from 0 (zero-indexed language).

py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

py_real_names[0]
# This should output "Natasha Romanoff".

py_super_names[0]
# This should output "Black Widow".

py_super_names[2] == py_super_names[-1]
# This should output True, since -1 means it counts from the back (reverse indexing).

True

## 1.3 Accessing data from a dictionary

In [2]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

superhero_info["Natasha Romanoff"]
# This should output the value "Black Widow" associated with the key "Natasha Romanoff".

'Black Widow'

In [3]:
# To access all keys and values respectively, we can use the 
# .keys() and .values() functions.

superhero_info.keys()
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [ ]:
# 2D Lists / Arrays

py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# Workaround to having two separate lists to store each info.

# 2 Lists vs. Arrays

## 2.1 Size

In [6]:
# We can use the len() function to find out the number of elements in a list / array.

import numpy as np

py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)     
# This reuses the Python list to create a NEW NumPy array.

len(py_list_2d)
len(np_array_2d)

np_array_2d.shape
# Note the absence of brackets above. This is because shape is NOT a function but
# rather a property or attribute of the NumPy array.

(10, 2)

## 2.2 Arrays are fussy about type

In [8]:
# Arrays are insistent about having only a SINGLE data type,
# while lists are more accomodating.

py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

py_list

[1, 1.5, 'A']

In [9]:
np_array
# Numpy will convert all the numbers into strings.

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [15]:
# NumPy will allow for the addition of numbers into a list.

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

py_list + 10      # Won't work!

# Instead, to add numbers to another list, we will have to use the .append() function.

TypeError: can only concatenate list (not "int") to list

In [11]:
np_array + 10

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [16]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

py_list_1 + py_list_2

# Adding two lists will simply append list 1 to list 2.

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [18]:
np_array_1 + np_array_2

# Adding two arrays will add each of the array elements together (element-wise operation).

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [19]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

py_list*2

# Multiplying lists will simply append the same list behind the original however many times.

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [20]:
np_array*2

# Multiplying arrays will multiply each element by the number.

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [21]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

py_list**2     # Won't work.

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [22]:
np_array**2

# Squares each element.

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [31]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

py_list == 3        # Works, but outputs FALSE. Why?

False

In [24]:
py_list > 3         # Won' work.

TypeError: '>' not supported between instances of 'list' and 'int'

In [25]:
np_array == 3

array([False, False,  True, False, False])

In [26]:
np_array > 3

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [33]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

sum(py_list)        # sum() is a base Python function

15

In [34]:
max(py_list)

5

In [35]:
min(py_list)

1

In [36]:
py_list.sum()          # Won't work!

AttributeError: 'list' object has no attribute 'sum'

In [37]:
np_array.sum()

15

In [38]:
np_array.max()

5

In [39]:
np_array.min()

1

In [40]:
np_array.mean()

3.0

In [41]:
np_array.std()

1.4142135623730951

An operation on a list works on the **whole** list, while operations on a array work on the **individual elements** of the array.

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes

### **Summary of Storing Data (Need)**