<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

**Subsetting**
Subsetting is the process of *selecting a subset of the data* in a list or array.
One form of this is picking a *single element* through **indexing** (see previous chapter).
Another option to *select a range of elements* is called **slicing**.

In short,
- **Subsetting**: To select
- **Indexing**: Selecting one element
- **Slicing**: Selecting a range of elements

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [2]:
import numpy as np

x = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
np_array = np.array(x)

x[0]       # Prints first element 'a1'.
x[-1]      # Prints last element 'j10'.
x[0:3]     # Prints first to third element 'a1', 'b2', 'c3'.
x[1:6]     # Prints second to sixth element.
x[1:6:2]   # Prints second to sixth element in steps of 2 ['b2', 'd4', 'f6'].
x[5: ]     # Prints sixth element to the end (gives len(x) - 5 elements)
x[:5]      # Prints first to sixth element (gives 5 elements)
x[5:2:-1]  # Prints index 5 to 3 (i.e. in reverse)
x[::-1]    # reverses the list

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

## 1.2 Arrays only | Subsetting by masking

In [5]:
# NumPy arrays can be subsetted by masking.

np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

# This returns an array in a TRUE / FALSE format.
# I can then use this TRUE / FALSE format to ask NumPy to show by the ones that are
# TRUE by using the following command.

np_array[my_mask]

# The TRUE / FALSE answer acts like a mask allowing only the TRUE subset to be seen.

array([ 4,  5,  6,  7,  8,  9, 10])

In [6]:
# To simplify this, we can write the following:
np_array[np_array > 3]

# This omits the need to create another variable.

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
# The mask can be inverted using ~. This is the Bitwise NOT operator.
np_array[~(np_array > 3)]
# This outputs array([1, 2, 3])

array([1, 2, 3])

In [10]:
# We can also combine one mask with another mask using the AND operator.
# AND will only show something if both masks are true.
# & is the Bitwise AND operator.

np_array[(np_array > 3) & (np_array < 8)]

array([4, 5, 6, 7])

In [11]:
# We can combine one mask OR another mask using | which is the Bitwise OR operator.

np_array[(np_array < 3) | (np_array > 8)]

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [15]:
# Differences between lists and arrays are more apparent in higher dimensional lists
# and arrays, especially when indexing / slicing in higher dimensions.

py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

# Q1. What is at position 4 (index 3)?
print(py_list_2d[3])

np_array_2d[3]

[4, 'D']


array(['4', 'D'], dtype='<U11')

In [17]:
# Q2. What is the FIRST element at position 4 (index 3)?

print(py_list_2d[3][0])
print(np_array_2d[3, 0])

# Note the syntax between lists and arrays.
# Arrays use a single pair of square brackets compared to lists.

4
4


In [18]:
# Q3. What are the first three elements?

print(py_list_2d[:3])

np_array_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]


array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [19]:
# Q4. 

print(py_list_2d[:3][0])
# Instead of printing the first elements of the three sublists (up to index 2, i.e. 
# [1, 2, 3], it instead returns the first of the list you get from py_list_2d[:3].

np_array_2d[:3, 0]
# NumPy arrays however, will obtain the correct thing.

[1, 'A']


array(['1', '2', '3'], dtype='<U11')

In [22]:
# Q5.

print(py_list_2d[3:6][0])
# This will return [4, 'D'], because it prints the 1D lists of index 3 to 5 within the
# 2D list py_list_2d, and then subsequently prints the first element of this sublist,
# which is [4, 'D'].

print(np_array_2d[3:6, 0])
# This returns array(['4', '5', '6'], because from the sublist of 1D lists of index 3 to 5,
# it will print the first element of each of the 1D list, which are the integers 4, 5, 6.

np_array_2d[:, 0]
# To return every first element of each of the 1D lists in the 2D lists, use the above
# syntax.

[4, 'D']
['4' '5' '6']


array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

## 1.4 Growing lists

In [25]:
# The slicing function of NumPy arrays is more intuitive with lists.
# What are some advantages of lists? Ease in efficiency in growing.
# NumPy arrays are great at math but provided their SIZE DOES NOT CHANGE.

# Below shows how to grow a list, which will be useful for in solving differential
# equations numerically.

x=[1,2]*5
print(x)

# Appending lists one element at a time:
x = [1]
x = x + [2]
x = x + [3]
x = x + [4]
print(x)

x=[1]
x+= [2]
x+= [3]
x+= [4]
print(x)   # Same syntax as above.

x=[1]
x.append(2)
x.append(3)
x.append(4)
print(x)   # Same syntax as above.

# Execution speeds are different between the above versions, with append() running 1.5
# times faster than the rest.

# Incorporating multiple elements:
x = [1, 2, 3]
x += [4, 5, 6]
print(x)

x = [1, 2, 3]
x.extend([4, 5, 6])
print(x)

x = [1, 2, 3]
x.append([4, 5, 6])
print(x)

# Take note of the difference in the result between extend and append.
# Append adds a list within the list, while extend continues the original list itself.


[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, [4, 5, 6]]


# Some loose ends

## 1.5 Tuples

In [29]:
# Tuples are similar to lists, except they use rounded brackets (  ) and cannot
# be changed after creation (i.e. they are immutable). 

a = (1, 2, 3)
print(a[0])

# The below will not work and gives a TypeError because tuples do not support
# item assignment.
'''
a[0] = -1
a[0] += [10]
'''


1


'\na[0] = -1\na[0] += [10]\n'

## 1.6 Be VERY careful when copying

In [31]:
# Do NOT copy the list as follows:
x = [1, 2, 3]
y = x
z = x
print(y)
print(z)

# Instead, we should use the copy() function to copy the list.
x = [1, 2, 3]
y = x.copy()
z = x.copy()
print(y)
print(z)


[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]


# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes